apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rbac.fullname" . }}-config
  labels:
    {{- include "rbac.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rbac.fullname" . }}-secret
  labels:
    {{- include "rbac.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
