# Generated by Django 5.1.4 on 2026-06-06 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, db_index=True, max_length=512)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied'), ('locked', 'Locked')], db_index=True, max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'audit_access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'result'], name='audit_acces_timesta_0d1f4d_idx'), models.Index(fields=['user', 'action'], name='audit_acces_user_id_88de29_idx'), models.Index(fields=['action', 'result'], name='audit_acces_action_2c0b0e_idx')],
            },
        ),
    ]
