# Generated by Django 5.1.4 on 2026-06-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_permissions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='permission',
            name='managed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
